swagger: "2.0"
info:
  description: "mi primera API"
  version: "1.0.0"
  title: "Mi artista favorito"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "miartistafavorito.swagger.io"
basePath: "/v2"
tags:
- name: "artista"
  description: "Mi artista favorito"
schemes:
- "https"
- "http"
paths:
  /artista/findAll:
    get:
      tags:
      - "artista"
      summary: "Entrega todos los artistas disponibles"
      description: "Entrega varios strings"
      operationId: "findAllArtist"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Artista"
        "400":
          description: "Invalid status value"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
  /producto:
    post:
      tags:
      - "Clientes"
      - "Administradores"
      summary: "Add a new pet to the store"
      description: ""
      operationId: "addPet"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Pet"
      responses:
        "405":
          description: "Invalid input"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
    put:
      tags:
      - "pet"
      summary: "Update an existing pet"
      description: ""
      operationId: "updatePet"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Pet"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
        "405":
          description: "Validation exception"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
definitions:
  Artista:
    type: "object"
    required:
    - "name"
    - "photoUrls"
    properties:
      name:
        type: "string"
        example: "Daft Punk"
      biografia:
        type: "string"
        example: "Daft Punk fue fundada..."  
      img-url:
        type: "string"
        example: "https://upload.wikimedia.org/wikipedia/commons/4/41/Daftpunklapremiere2010.jpg"
      discografia:
        type: "string"
        description: "Discos del artista"
        enum:
        - "1997: Homework"
        - "2001: Discovery"
        - "2005: Human After All"
        - "2013: Random Access Memories"   
      spotify:
        type: "string"
        example: "https://open.spotify.com/playlist/5vHzkmyNj3j6IC7Hfq0n0u"
    xml:
      name: "Artista"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"